#!/bin/sh
# cdfi
# Current Directory & Files Information >> cdfi
# Writes out the current working dir then lists all of the files and dirs from it

input=$1
path=""
# check if the input is empty or not. If it is list the cwd if not list the inputed path
[ -z "$input" ] && path="." || path="$input"
[ -z "$input" ] && pwd || echo "$input"
echo -n "\n\033[1;34m"
ls -alh $path | grep ^d | awk '{print $0;$9}'
echo -n "\033[1;36m"
ls -alh $path | grep ^l | awk '{print $0;$9}'
echo -n "\033[1;32m"
ls -alph $path | grep -v / | grep -v '^total'
